"""Run the MOEA/D tutorial and optionally save an actual-result SVG.

Use a checkout with VAMOS installed; plotting additionally needs matplotlib.
Existing output files are refused. No output is written without --output.
"""

from __future__ import annotations

import argparse
import json
from io import StringIO
from pathlib import Path

import numpy as np

from vamos import OptimizationResult, optimize
from vamos.algorithms import MOEADConfig
from vamos.problems import ZDT1


def solve(*, pop_size: int = 100, max_evaluations: int = 10_000, seed: int = 42) -> OptimizationResult:
    """Run the tutorial with explicit dimension, budget, seed and backend."""
    problem = ZDT1(n_var=30)
    config = MOEADConfig.default(pop_size=pop_size, n_var=problem.n_var, n_obj=problem.n_obj)
    return optimize(
        problem,
        algorithm="moead",
        algorithm_config=config,
        max_evaluations=max_evaluations,
        engine="numpy",
        seed=seed,
    )


def plot_result(result: OptimizationResult, output: Path) -> None:
    """Plot returned objective values, with a labelled analytical reference."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if result.F is None or result.F.ndim != 2 or result.F.shape[1] != 2 or len(result.F) == 0:
        raise ValueError("The illustration requires non-empty 2-objective results.")
    if output.suffix.lower() != ".svg":
        raise ValueError("Use an .svg output path.")
    if output.exists():
        raise FileExistsError(f"Refusing to overwrite {output}. Choose a new output path.")
    output.parent.mkdir(parents=True, exist_ok=True)
    with plt.rc_context({"svg.fonttype": "none", "svg.hashsalt": "vamos-moead-tutorial"}):
        fig, ax = plt.subplots(figsize=(7.2, 4.6), layout="constrained")
        f1 = np.linspace(0.0, 1.0, 201)
        ax.plot(f1, 1.0 - np.sqrt(f1), "--", lw=1.5, label="Analytical Pareto front")
        ax.scatter(result.F[:, 0], result.F[:, 1], s=22, label="MOEA/D returned solutions", zorder=3)
        ax.set(xlabel="Objective 1 (minimize)", ylabel="Objective 2 (minimize)", title="MOEA/D on ZDT1")
        ax.legend(frameon=False, fontsize=9)
        try:
            description = (
                "Generated by examples/journeys/moead_zdt1.py; "
                f"{len(result.F)} returned solutions; {result.data['evaluations']} evaluations. "
                "The dashed line is f2 = 1 - sqrt(f1), not an optimization result."
            )
            buffer = StringIO()
            fig.savefig(buffer, format="svg", metadata={"Date": None, "Description": description})
            svg = "\n".join(line.rstrip() for line in buffer.getvalue().splitlines()) + "\n"
            with output.open("x", encoding="utf-8", newline="\n") as handle:
                handle.write(svg)
        finally:
            plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pop-size", type=int, default=100)
    parser.add_argument("--max-evaluations", type=int, default=10_000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output", type=Path, help="Optional new SVG path; requires matplotlib.")
    args = parser.parse_args()
    if args.pop_size < 4 or args.max_evaluations < args.pop_size:
        parser.error("pop-size must be at least 4 and max-evaluations must cover the initial population")
    if args.output is not None and (args.output.exists() or args.output.suffix.lower() != ".svg"):
        parser.error("output must be a new .svg path")
    result = solve(pop_size=args.pop_size, max_evaluations=args.max_evaluations, seed=args.seed)
    if result.X is None or result.F is None:
        raise RuntimeError("MOEA/D did not return solution arrays.")
    if args.output is not None:
        plot_result(result, args.output)
    print(
        json.dumps(
            {
                "algorithm": "moead",
                "problem": "zdt1",
                "n_var": 30,
                "engine": "numpy",
                "seed": args.seed,
                "pop_size": args.pop_size,
                "evaluations": result.data["evaluations"],
                "X_shape": list(result.X.shape),
                "F_shape": list(result.F.shape),
                "figure": str(args.output) if args.output is not None else None,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
