"""Run the NSGA-III tutorial and optionally save an actual-result SVG.

Use a checkout with VAMOS installed; plotting additionally needs matplotlib.
Existing output files are refused. No output is written without --output.
"""

from __future__ import annotations

import argparse
import json
from io import StringIO
from math import comb
from pathlib import Path

import numpy as np

from vamos import OptimizationResult, optimize
from vamos.algorithms import NSGAIIIConfig
from vamos.problems import DTLZ2


def solve(*, divisions: int = 12, max_evaluations: int = 10_000, seed: int = 42) -> OptimizationResult:
    """Run the tutorial with explicit dimension, budget, seed and backend."""
    problem = DTLZ2(n_var=12, n_obj=3)
    pop_size = comb(divisions + problem.n_obj - 1, problem.n_obj - 1)
    config = (
        NSGAIIIConfig.builder()
        .pop_size(pop_size)
        .crossover("sbx", prob=1.0, eta=30.0)
        .mutation("pm", prob="1/n", eta=20.0)
        .selection("tournament")
        .reference_directions(divisions=divisions)
        .result_mode("population")
        .build()
    )
    return optimize(
        problem,
        algorithm="nsgaiii",
        algorithm_config=config,
        max_evaluations=max_evaluations,
        engine="numpy",
        seed=seed,
    )


def plot_result(result: OptimizationResult, output: Path) -> None:
    """Plot returned objective values, with a labelled analytical reference."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if result.F is None or result.F.ndim != 2 or result.F.shape[1] != 3 or len(result.F) == 0:
        raise ValueError("The illustration requires non-empty 3-objective results.")
    if output.suffix.lower() != ".svg":
        raise ValueError("Use an .svg output path.")
    if output.exists():
        raise FileExistsError(f"Refusing to overwrite {output}. Choose a new output path.")
    output.parent.mkdir(parents=True, exist_ok=True)
    with plt.rc_context({"svg.fonttype": "none", "svg.hashsalt": "vamos-nsgaiii-tutorial"}):
        fig = plt.figure(figsize=(7.2, 5.4), layout="constrained")
        ax = fig.add_subplot(projection="3d")
        u, v = np.meshgrid(np.linspace(0.0, np.pi / 2, 7), np.linspace(0.0, np.pi / 2, 7))
        ax.plot_wireframe(
            np.cos(u) * np.cos(v),
            np.cos(u) * np.sin(v),
            np.sin(u),
            color="#94a3b8",
            alpha=0.45,
            linewidth=0.6,
            label="Analytical Pareto surface",
        )
        ax.scatter(
            result.F[:, 0], result.F[:, 1], result.F[:, 2], s=18, color="#087e8b", label="NSGA-III final population", depthshade=False
        )
        ax.set(xlabel="Objective 1", ylabel="Objective 2", zlabel="Objective 3", title="NSGA-III on DTLZ2 | all objectives minimized")
        ax.view_init(elev=24, azim=38)
        ax.legend(frameon=False, fontsize=8, loc="upper left")
        try:
            description = (
                "Generated by examples/journeys/nsgaiii_dtlz2.py; "
                f"{len(result.F)} returned solutions; {result.data['evaluations']} evaluations. "
                "The wireframe is the positive octant of the unit sphere, not an optimization result."
            )
            buffer = StringIO()
            fig.savefig(buffer, format="svg", metadata={"Date": None, "Description": description})
            svg = "\n".join(line.rstrip() for line in buffer.getvalue().splitlines()) + "\n"
            with output.open("x", encoding="utf-8", newline="\n") as handle:
                handle.write(svg)
        finally:
            plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--divisions", type=int, default=12)
    parser.add_argument("--max-evaluations", type=int, default=10_000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output", type=Path, help="Optional new SVG path; requires matplotlib.")
    args = parser.parse_args()
    if args.divisions < 1 or args.max_evaluations < comb(args.divisions + 2, 2):
        parser.error("divisions must be positive and max-evaluations must cover the direction count")
    if args.output is not None and (args.output.exists() or args.output.suffix.lower() != ".svg"):
        parser.error("output must be a new .svg path")
    result = solve(divisions=args.divisions, max_evaluations=args.max_evaluations, seed=args.seed)
    if result.X is None or result.F is None:
        raise RuntimeError("NSGA-III did not return solution arrays.")
    if args.output is not None:
        plot_result(result, args.output)
    print(
        json.dumps(
            {
                "algorithm": "nsgaiii",
                "problem": "dtlz2",
                "n_var": 12,
                "engine": "numpy",
                "seed": args.seed,
                "pop_size": comb(args.divisions + 2, 2),
                "evaluations": result.data["evaluations"],
                "X_shape": list(result.X.shape),
                "F_shape": list(result.F.shape),
                "figure": str(args.output) if args.output is not None else None,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
