"""Run the canonical NSGA-II tutorial; optionally save its ZDT1 illustration.

Run from a checkout with VAMOS installed. Plotting additionally needs matplotlib.
Outputs are written only when --output is given, and existing files are refused.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from io import StringIO
from pathlib import Path
from xml.etree import ElementTree

import numpy as np

from vamos import OptimizationResult, optimize
from vamos.algorithms import NSGAIIConfig
from vamos.problems import ZDT1


def solve(*, pop_size: int = 100, max_evaluations: int = 10_000, seed: int = 42) -> OptimizationResult:
    """Return a seeded real-coded run with an explicit NumPy backend."""
    problem = ZDT1(n_var=30)
    config = NSGAIIConfig.default(pop_size=pop_size, n_var=problem.n_var)
    return optimize(
        problem,
        algorithm="nsgaii",
        algorithm_config=config,
        max_evaluations=max_evaluations,
        engine="numpy",
        seed=seed,
    )


def _compact_svg(svg: str) -> str:
    """Deduplicate exporter styles without modifying any plotted coordinates."""
    namespaces = {
        "": "http://www.w3.org/2000/svg",
        "xlink": "http://www.w3.org/1999/xlink",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "dc": "http://purl.org/dc/elements/1.1/",
        "cc": "http://creativecommons.org/ns#",
    }
    for prefix, uri in namespaces.items():
        ElementTree.register_namespace(prefix, uri)
    root = ElementTree.fromstring(svg)
    counts = Counter(node.get("style") for node in root.iter() if node.get("style"))
    repeated = {style: f"s{index}" for index, (style, count) in enumerate(counts.items()) if count > 1}
    sheet = root.find("{http://www.w3.org/2000/svg}defs/{http://www.w3.org/2000/svg}style")
    assert sheet is not None
    sheet.text = (sheet.text or "") + "".join(f".{name}{{{style}}}" for style, name in repeated.items())
    for node in root.iter():
        style = node.get("style")
        if style in repeated:
            node.set("class", repeated[style])
            del node.attrib["style"]
        if node.text is not None and not node.text.strip():
            node.text = None
        node.tail = None
    return ElementTree.tostring(root, encoding="unicode") + "\n"


def plot_result(result: OptimizationResult, output: Path) -> None:
    """Save the returned objectives and the analytical front as an SVG.

    Import matplotlib only for this optional step. The analytical line is for
    interpretation; it is not supplied to NSGA-II and is not experimental data.
    """
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if result.F is None or result.F.ndim != 2 or result.F.shape[1] != 2 or len(result.F) == 0:
        raise ValueError("The illustration requires a non-empty, two-objective result.")
    if output.suffix.lower() != ".svg":
        raise ValueError("Use an .svg output path.")
    if output.exists():
        raise FileExistsError(f"Refusing to overwrite {output}. Choose a new output path.")
    output.parent.mkdir(parents=True, exist_ok=True)
    with plt.rc_context({"svg.fonttype": "none", "svg.hashsalt": "vamos-nsgaii-tutorial"}):
        fig, ax = plt.subplots(figsize=(7.2, 4.6), layout="constrained")
        try:
            f1 = np.linspace(0.0, 1.0, 301)
            ax.plot(f1, 1.0 - np.sqrt(f1), linestyle="--", linewidth=1.6, label="Analytical Pareto front")
            ax.scatter(result.F[:, 0], result.F[:, 1], s=22, label="NSGA-II returned solutions", zorder=3)
            ax.set(xlabel="Objective 1 (minimize)", ylabel="Objective 2 (minimize)", title="NSGA-II on ZDT1")
            ax.legend(loc="upper right", frameon=False, fontsize=9)
            ax.margins(0.05)
            description = (
                "Generated by examples/journeys/nsgaii_zdt1.py; "
                f"{len(result.F)} returned solutions; {result.data['evaluations']} evaluations. "
                "The dashed line is f2 = 1 - sqrt(f1), not an optimization result."
            )
            buffer = StringIO()
            fig.savefig(buffer, format="svg", metadata={"Date": None, "Description": description})
            svg = _compact_svg(buffer.getvalue())
            with output.open("x", encoding="utf-8", newline="\n") as handle:
                handle.write(svg)
        finally:
            plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pop-size", type=int, default=100)
    parser.add_argument("--max-evaluations", type=int, default=10_000)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output", type=Path, help="Optional new SVG path; requires matplotlib.")
    args = parser.parse_args()
    if args.pop_size <= 0 or args.max_evaluations < args.pop_size:
        parser.error("pop-size must be positive and max-evaluations must cover the initial population")
    if args.output is not None and (args.output.exists() or args.output.suffix.lower() != ".svg"):
        parser.error("output must be a new .svg path")
    result = solve(pop_size=args.pop_size, max_evaluations=args.max_evaluations, seed=args.seed)
    if result.X is None or result.F is None:
        raise RuntimeError("NSGA-II did not return solution arrays.")
    if args.output is not None:
        plot_result(result, args.output)
    print(
        json.dumps(
            {
                "algorithm": "nsgaii",
                "problem": "zdt1",
                "n_var": 30,
                "engine": "numpy",
                "seed": args.seed,
                "pop_size": args.pop_size,
                "evaluations": result.data["evaluations"],
                "X_shape": list(result.X.shape),
                "F_shape": list(result.F.shape),
                "figure": str(args.output) if args.output is not None else None,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
