"""Check the executable MOEA/D and NSGA-III learning paths."""

from __future__ import annotations

import json
import re
import runpy
import subprocess
import sys
from pathlib import Path
from xml.etree import ElementTree

import numpy as np
import pytest

from vamos import optimize
from vamos.algorithms import NSGAIIIConfig, RVEAConfig
from vamos.problems import DTLZ2, ZDT1

ROOT = Path(__file__).resolve().parents[2]
CASES = [("moead", "moead_zdt1", 30, 2), ("nsgaiii", "nsgaiii_dtlz2", 12, 3)]


@pytest.mark.parametrize(("algorithm", "script", "n_var", "n_obj"), CASES)
def test_tutorial_code_matches_generator_and_problem(algorithm, script, n_var, n_obj):
    page = ROOT / "docs" / "algorithms" / f"{algorithm}.md"
    code = re.findall(r"```python\n(.*?)\n```", page.read_text(), re.DOTALL)[0]
    namespace = {}
    exec(compile(code, str(page), "exec"), namespace)
    result = namespace["result"]
    example = runpy.run_path(str(ROOT / "examples" / "journeys" / f"{script}.py"))
    generated = example["solve"]()
    np.testing.assert_array_equal(result.X, generated.X)
    np.testing.assert_array_equal(result.F, generated.F)
    assert result.X.shape == (len(result.F), n_var)
    assert result.F.shape[1] == n_obj
    assert np.isfinite(result.F).all()
    assert np.all((result.X >= 0) & (result.X <= 1))
    assert result.data["evaluations"] == 10_000
    problem = ZDT1(n_var=30) if algorithm == "moead" else DTLZ2(n_var=12, n_obj=3)
    evaluated = np.empty_like(result.F)
    problem.evaluate(result.X, {"F": evaluated})
    np.testing.assert_allclose(result.F, evaluated)
    if algorithm == "nsgaiii":
        assert result.F.shape == (91, 3)
        assert result.data["reference_directions"].shape == (91, 3)
    else:
        dominates = np.all(result.F[:, None] <= result.F[None, :], axis=2)
        dominates &= np.any(result.F[:, None] < result.F[None, :], axis=2)
        assert not np.any(dominates)


@pytest.mark.parametrize(("algorithm", "script", "n_var", "n_obj"), CASES)
def test_tutorial_smoke_has_exact_partial_budget_and_no_output(tmp_path, algorithm, script, n_var, n_obj):
    option = ["--pop-size", "20"] if algorithm == "moead" else ["--divisions", "3"]
    completed = subprocess.run(
        [sys.executable, str(ROOT / "examples" / "journeys" / f"{script}.py"), *option, "--max-evaluations", "203"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=True,
    )
    report = json.loads(completed.stdout)
    assert report["evaluations"] == 203
    assert report["n_var"] == n_var
    assert report["F_shape"][1] == n_obj
    assert report["engine"] == "numpy" and report["seed"] == 42
    assert report["figure"] is None
    assert list(tmp_path.iterdir()) == []


@pytest.mark.parametrize(("algorithm", "script", "n_var", "n_obj"), CASES)
def test_tutorial_svg_provenance_and_overwrite_refusal(tmp_path, algorithm, script, n_var, n_obj):
    pytest.importorskip("matplotlib")
    example = runpy.run_path(str(ROOT / "examples" / "journeys" / f"{script}.py"))
    settings = {"pop_size": 20} if algorithm == "moead" else {"divisions": 3}
    result = example["solve"](max_evaluations=203, **settings)
    output = tmp_path / "result.svg"
    example["plot_result"](result, output)
    assert ElementTree.parse(output).getroot().tag == "{http://www.w3.org/2000/svg}svg"
    original = output.read_bytes()
    assert b"203 evaluations" in original and b"not an optimization result" in original
    with pytest.raises(FileExistsError):
        example["plot_result"](result, output)
    assert output.read_bytes() == original
    maintained = ROOT / "docs" / "assets" / "algorithms" / f"{script.replace('_', '-')}.svg"
    text = maintained.read_text()
    assert f"Generated by examples/journeys/{script}.py" in text
    assert "10000 evaluations" in text and "<script" not in text


def test_nsgaiii_documented_cardinality_rejection():
    config = (
        NSGAIIIConfig.builder()
        .pop_size(12)
        .crossover("sbx", prob=1.0, eta=30.0)
        .mutation("pm", prob="1/n", eta=20.0)
        .selection("tournament")
        .reference_directions(divisions=3)
        .build()
    )
    with pytest.raises(ValueError, match="expect 10 points"):
        optimize(DTLZ2(n_var=12, n_obj=3), algorithm="nsgaiii", algorithm_config=config, max_evaluations=203, seed=42)


@pytest.mark.parametrize("algorithm", ["nsgaii", "nsgaiii", "moead", "smsemoa", "spea2", "ibea", "smpso", "agemoea", "rvea"])
@pytest.mark.parametrize("engine", ["numpy", "numba", "moocore"])
def test_catalogue_real_unconstrained_backend_combinations(algorithm, engine):
    if engine != "numpy":
        pytest.importorskip(engine)
    problem = ZDT1(n_var=6)
    kwargs = {"pop_size": 12}
    if algorithm == "nsgaiii":
        kwargs = {
            "algorithm_config": NSGAIIIConfig.builder()
            .pop_size(12)
            .crossover("sbx", prob=1.0, eta=30.0)
            .mutation("pm", prob="1/n", eta=20.0)
            .selection("tournament")
            .reference_directions(divisions=11)
            .build()
        }
    elif algorithm == "rvea":
        kwargs = {
            "algorithm_config": RVEAConfig.builder()
            .pop_size(12)
            .n_partitions(11)
            .alpha(2.0)
            .crossover("sbx", prob=1.0, eta=30.0)
            .mutation("pm", prob=1 / problem.n_var, eta=20.0)
            .build()
        }
    result = optimize(problem, algorithm=algorithm, engine=engine, max_evaluations=37, seed=42, **kwargs)
    assert result.data["evaluations"] == 37
    assert result.F is not None and result.F.shape[1] == 2 and len(result.F) > 0
    assert np.isfinite(result.F).all()
